services:
  mariadb:
    container_name: mariadb
    build:
      context: ./mariadb
      dockerfile: Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wp_user
      - MYSQL_PASSWORD=password
      - HOST_UID=${HOST_UID:-1000} 
    networks:
      - docker-network
    volumes:
      - data_mariadb:/var/lib/mysql
    restart: unless-stopped

  webserv:
    container_name: webserv
    build:
      context: ../
      dockerfile: ./docker/webserv/Dockerfile
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - DOMAIN_NAME="localhost:8080"
      - DB_HOST=mariadb
      - DB_PORT=3306

      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wp_user
      - MYSQL_PASSWORD=password

      - WP_TITLE="webserv blog"
      - WP_DESCRIPTION=""
      - WP_THEME=my-minimalist-blog

      - WP_ADMIN=admin
      - WP_ADMIN_PASSWORD=admin
      - WP_ADMIN_EMAIL=admin@wordpress.com
      - WP_USER=author
      - WP_USER_PASSWORD=author
      - WP_USER_EMAIL=user@wordpress.com
    networks:
      - docker-network
    ports:
      # - '80:80'
      - '8080:8080'
      - '8081:8081'
      - '8082:8082'
      
    volumes:
      # - data_htdocs:/webserv/htdocs
      - data_wordpress:/webserv/htdocs
    restart: unless-stopped

networks:
  docker-network:
    name: docker-network

volumes:
  data_mariadb:
    name: data_mariadb
    # driver: local
    # driver_opts:
    #   type: none
    #   device: data/mariadb
    #   o: bind
  # data_htdocs:
  #   name: data_htdocs
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: ../htdocs
  #     o: bind
  data_wordpress:
    name: data_wordpress
    driver: local
    driver_opts:
      type: none
      device: data/wordpress
      o: bind
